'use client';

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Category } from '../../types';
import { categoryService } from '../../services/category.service';
import { configKeys } from '../../configKeys';

interface CategoryEditorProps {
    initialData?: Category;
    isEditing?: boolean;
    categoryId?: number | string;
}

export default function CategoryEditor({ initialData, isEditing = false, categoryId }: CategoryEditorProps) {
    const router = useRouter();
    const [name, setName] = useState('');

    const [description, setDescription] = useState('');
    const [thumbnail, setThumbnail] = useState('');
    const [parentId, setParentId] = useState<number | string>(0);
    const [status, setStatus] = useState('active');

    const [categories, setCategories] = useState<Category[]>([]);
    const [saving, setSaving] = useState(false);
    const [uploading, setUploading] = useState(false);
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        loadData();
    }, [categoryId]);

    const loadData = async () => {
        setLoading(true);
        try {
            // Load parent categories for selection
            const parents = await categoryService.getParents();
            setCategories(parents);

            if (isEditing && categoryId) {
                // If we don't have initialData, fetch it
                if (!initialData) {
                    const cat = await categoryService.getById(categoryId);
                    if (cat) {
                        setName(cat.name);
                        setDescription(cat.description || '');
                        setThumbnail(cat.thumbnail || '');
                        setParentId(cat.parent || 0);
                        setStatus(cat.status || 'active');
                    }
                }
            }
        } catch (error) {
            console.error('Error loading data:', error);
            alert('Error loading data');
        } finally {
            setLoading(false);
        }
    };

    // If initialData is provided directly (e.g. from server component)
    useEffect(() => {
        if (initialData) {
            setName(initialData.name);
            setDescription(initialData.description || '');
            setThumbnail(initialData.thumbnail || '');
            setParentId(initialData.parent || 0);
            setStatus(initialData.status || 'active');
        }
    }, [initialData]);


    const handleThumbnailUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) return;

        setUploading(true);
        try {
            // Use our new uploadFile method
            const url = await categoryService.uploadFile(file);
            setThumbnail(url);
        } catch (error) {
            console.error('Failed to upload thumbnail', error);
            alert('Failed to upload thumbnail');
        } finally {
            setUploading(false);
        }
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setSaving(true);

        // Helper to strip base URL for saving
        const stripBaseUrl = (url: string) => {
            const baseUrl = configKeys.GEMINI_NEW_BASE_URL.replace(/\/$/, '');
            if (url.startsWith(baseUrl)) {
                return url.replace(baseUrl, '');
            }
            return url;
        };

        const submitData: Partial<Category> = {
            name,
            description,
            thumbnail: stripBaseUrl(thumbnail),
            parent: Number(parentId),
            status,
            tax_status: 'taxable',
            tax_class: '',
            // Slug is usually auto-generated by backend, but we can generate it here if needed
            // slug: name.toLowerCase().replace(/ /g, '-').replace(/[^\w-]+/g, ''),
        };

        try {
            if (isEditing && categoryId) {
                await categoryService.update(categoryId, submitData);
            } else {
                await categoryService.create(submitData);
            }
            router.push('/dashboard/categories');
            router.refresh();
        } catch (error) {
            console.error('Failed to save category', error);
            alert('Failed to save category');
        } finally {
            setSaving(false);
        }
    };

    if (loading && isEditing) {
        return <div style={{ padding: '2rem', textAlign: 'center' }}>Loading...</div>;
    }

    return (
        <div className="glass-panel p-8 max-w-[800px] mx-auto border border-border">
            <form onSubmit={handleSubmit} className="flex flex-col gap-6">
                <div className="flex flex-col gap-2">
                    <label className="font-medium text-text-muted">Name</label>
                    <input
                        type="text"
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                        required
                        className="p-3 rounded-md border border-border bg-white/5 text-text-main w-full focus:outline-none focus:ring-1 focus:ring-primary transition-all"
                    />
                </div>

                <div className="flex flex-col gap-2">
                    <label className="font-medium text-text-muted">Description</label>
                    <textarea
                        value={description}
                        onChange={(e) => setDescription(e.target.value)}
                        rows={4}
                        className="p-3 rounded-md border border-border bg-white/5 text-text-main w-full focus:outline-none focus:ring-1 focus:ring-primary transition-all font-inherit"
                    />
                </div>

                <div className="flex flex-col gap-2">
                    <label className="font-medium text-text-muted">Parent Category</label>
                    <select
                        value={parentId}
                        onChange={(e) => setParentId(e.target.value)}
                        className="p-3 rounded-md border border-border bg-white/5 text-text-main w-full focus:outline-none focus:ring-1 focus:ring-primary transition-all"
                    >
                        <option value={0} className="bg-surface">None (Top Level)</option>
                        {categories.filter(c => c._id != categoryId).map((cat) => (
                            <option key={cat.term_id} value={cat.term_id} className="bg-surface">
                                {cat.name}
                            </option>
                        ))}
                    </select>
                </div>

                <div className="flex flex-col gap-2">
                    <label className="font-medium text-text-muted">Status</label>
                    <select
                        value={status}
                        onChange={(e) => setStatus(e.target.value)}
                        className="p-3 rounded-md border border-border bg-white/5 text-text-main w-full focus:outline-none focus:ring-1 focus:ring-primary transition-all"
                    >
                        <option value="active" className="bg-surface">Active</option>
                        <option value="archived" className="bg-surface">Archived</option>
                    </select>
                </div>


                <div className="flex flex-col gap-2">
                    <label className="font-medium text-text-muted">Thumbnail</label>
                    <div className="flex gap-4 items-center">
                        <div className="flex-1">
                            <input
                                type="text"
                                value={thumbnail}
                                onChange={(e) => setThumbnail(e.target.value)}
                                className="p-3 rounded-md border border-border bg-white/5 text-text-main w-full focus:outline-none focus:ring-1 focus:ring-primary transition-all"
                                placeholder="Image URL"
                            />
                        </div>
                        <label className="flex items-center justify-center p-3 border border-border rounded-md cursor-pointer bg-white/5 whitespace-nowrap hover:bg-white/10 transition-colors">
                            {uploading ? 'Uploading...' : 'Upload'}
                            <input type="file" accept="image/*" onChange={handleThumbnailUpload} className="hidden" disabled={uploading} />
                        </label>
                    </div>
                    {thumbnail && (
                        <div className="mt-2 w-[100px] h-[100px] rounded-md overflow-hidden border border-border">
                            <img src={thumbnail} alt="Thumbnail preview" className="w-full h-full object-cover" />
                        </div>
                    )}
                </div>

                <div className="flex justify-end gap-4 mt-4">
                    <button
                        type="button"
                        onClick={() => router.back()}
                        className="px-6 py-3 rounded-md border border-border bg-transparent text-text-main cursor-pointer hover:bg-white/5 transition-colors"
                    >
                        Cancel
                    </button>
                    <button
                        type="submit"
                        disabled={saving}
                        className="px-6 py-3 rounded-md border-none bg-primary text-white cursor-pointer font-semibold transition-all disabled:opacity-70 hover:bg-primary-hover"
                    >
                        {saving ? 'Saving...' : (isEditing ? 'Update Category' : 'Create Category')}
                    </button>
                </div>
            </form>
        </div>
    );
}
